#### Parsing options ####
DoclingParser_options:
  accelerator:
    device: "cuda" # "auto" or "cpu" or "cuda" or "mps"
    num_threads: 8
  

parser_options:
  parser: "docling"
  save_parsed_content: True
  output_dir: "markdown"
  parser_options: "DoclingParser_options"



#### Chunking options ####
SemanticChunking_options:
  model: "minishlab/potion-base-8M"
  similarity_threshold: 0.75
  double_pass_merge: True
  chunk_size: 1536
  device: "mps" # "cuda", "cpu", "mps", "npu"

  
Chunker:
  chunking_method: "Semantic"
  chunking_options: "SemanticChunking_options"



### Weaviate options ###
Weaviate_options:
  collection_name: "V3_docling_semantic_nomic"
  vectorizer: "nomic-embed-text:v1.5" 
  reranker: "BAAI/bge-reranker-v2-m3"
  generator: "qwen3:1.7b"


Backend:
  file_system: "/app/data/documents"
  # file_system_server: "http://ec2-3-15-20-187.us-east-2.compute.amazonaws.com:8002" # pdf_server:8002 # VAST_IP:8002
  file_system_server: "http://3.142.235.103/pdfs"
  data_map: "data_map.json"
  prompt_map: "prompt_map.json"

