#### Parsing options ####
DoclingParser_options:
  accelerator:
    device: "cuda" # "auto" or "cpu" or "cuda" or "mps"
    num_threads: 8
  

parser_options:
  parser: "docling"
  save_parsed_content: True
  output_dir: "markdown"
  parser_options: "DoclingParser_options"



#### Chunking options ####
LayoutChunking_options:
  min_words: 30
  

Chunker:
  chunking_method: "layout"
  chunking_options: "LayoutChunking_options"



### Weaviate options ###
Weaviate_options:
  collection_name: "alpha_v0"
  vectorizer: "bge-m3" 
  reranker: "BAAI/bge-reranker-v2-m3"
  generator: "qwen2.5:latest"


Backend:
  file_system: "/app/data/documents"
  file_system_server: "http://ec2-3-15-20-187.us-east-2.compute.amazonaws.com:8002" # pdf_server:8002 # VAST_IP:8002
  data_map: "data_map.json"
  prompt_map: "prompt_map.json"

